<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypesxsd="http://www.w3.org/2001/XMLSchema-instance"?>
<package format="3">
  <name>av_planning_py</name>
  <version>0.1.0</version>
  <description>全局/局部路径规划节点</description>
  <maintainer email="tiger@example.com">tiger</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>av_carla_interfaces</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
